def checkColumn(fle, fleName):
    import pandas as pd
    from pandas import ExcelWriter
    from pandas import ExcelFile
    import numpy as np

    if(fleName == 'Academic_Events.xlsx'):
        columnNames= [
        "SUBJECT_AREA",
        "SAMPLE_QUESTION",
        "ENTITY_TYPE",
        # "INTENT",
        "COPIED_FROM",
        "ENTITY_NAME",
        "SECONDARY_ENTITY_NAME",
        "KEYWORD",
        "DESCRIPTION",
        "PRESENTER",
        "START_DATE",
        "END_DATE",
        "OCCURANCE",
        "WEEKDAY_START_TIME",
        "WEEKDAY_END_TIME",
        "WEEKEND_START_TIME",
        "WEEKEND_END_TIME",
        "MON_START_TIME",
        "MON_END_TIME",
        "TUE_START_TIME",
        "TUE_END_TIME",
        "WED_START_TIME",
        "WED_END_TIME",
        "THU_START_TIME",
        "THU_END_TIME",
        "FRI_START_TIME",
        "FRI_END_TIME",
        "SAT_START_TIME",
        "SAT_END_TIME",
        "SUN_START_TIME",
        "SUN_END_TIME",
        "EXCEPTION_TEXT",
        "TEXT",
        "VOICE",
        "VOICE_ONLY",
        "PHONE",
        "EMAIL",
        "LOCATION",
        "LATITUDE",
        "LONGITUDE",
        "REF_URL",
        "MEDIA",
        "LANGUAGES",
        "PROCESS_AGENT_ID",
        "PROCESS_ID"
        ]
    elif(fleName == 'Campus_Events.xlsx'):
        columnNames = [
        "ENTITY_TYPE",
        "ENTITY_NAME",
        "SECONDARY_ENTITY_NAME",
        "KEYWORD",
        "DESCRIPTION",
        "PRESENTER",
        "START_DATE",
        "END_DATE",
        "START_TIME",
        "END_TIME",
        "WEEKDAY_START_TIME",
        "WEEKDAY_END_TIME",
        "WEEKEND_START_TIME",
        "WEEKEND_END_TIME",
        "MON_START_TIME",
        "MON_END_TIME",
        "TUE_START_TIME",
        "TUE_END_TIME",
        "WED_START_TIME",
        "WED_END_TIME",
        "THU_START_TIME",
        "THU_END_TIME",
        "FRI_START_TIME",
        "FRI_END_TIME",
        "SAT_START_TIME",
        "SAT_END_TIME",
        "SUN_START_TIME",
        "SUN_END_TIME",
        "EXCEPTION_TEXT",
        "TEXT",
        "VOICE",
        "VOICE_ONLY",
        "PHONE",
        "EMAIL",
        "LOCATION",
        "LATITUDE",
        "LONGITUDE",
        "REF_URL"
        ]
    elif(fleName == 'Contact.xlsx'):
        columnNames= [
        "SUBJECT_AREA",
        # "SAMPLE_QUESTIONS",
        "ENTITY_TYPE",
        "COPIED_FROM",
        "ENTITY_NAME",
        "SECONDARY_ENTITY_NAME",
        "KEYWORD",
        "DESCRIPTION",
        "LATITUDE",
        "LONGITUDE",
        "MAP_URL",
        "SHORT_URL",
        "PERSON",
        "PHONE",
        "EMAIL",
        "FAX",
        "TEXT",
        "VOICE",
        "VOICE_ONLY",
        "REF_URL",
        "MEDIA",
        "LANGUAGES",
        "PROCESS_AGENT_ID",
        "PROCESS_ID"
        ]
    elif(fleName == 'Location.xlsx'):
        columnNames = [
        # "SUBJECT_AREA",
        # "SAMPLE_QUESTIONS",
        "ENTITY_TYPE",
        "ENTITY_NAME",
        "SECONDARY_ENTITY_NAME",
        "KEYWORD",
        "DESCRIPTION",
        "LATITUDE",
        "LONGITUDE",
        "MAP_URL",
        "SHORT_URL",
        "PERSON",
        "PHONE",
        "EMAIL",
        "FAX",
        "TEXT",
        "VOICE",
        "VOICE_ONLY",
        "REF_URL",
        "MEDIA",
        "LANGUAGES",
        "PROCESS_AGENT_ID",
        "PROCESS_ID"
        ]
    elif(fleName == 'Timing.xlsx'):
        columnNames = [
        "SUBJECT_AREA",
       # "SAMPLE_QUESTIONS",
        "ENTITY_TYPE",
       # "COPIED_FROM",
        "ENTITY_NAME",
        "SECONDARY_ENTITY_NAME",
        "KEYWORD",
        "DESCRIPTION",
        "PRESENTER",
        "START_DATE",
        "END_DATE",
        "START_TIME",
        "END_TIME",
        "OCCURANCE",
        "WEEKDAY_START_TIME",
        "WEEKDAY_END_TIME",
        "WEEKEND_START_TIME",
        "WEEKEND_END_TIME",
        "MON_START_TIME",
        "MON_END_TIME",
        "TUE_START_TIME",
        "TUE_END_TIME",
        "WED_START_TIME",
        "WED_END_TIME",
        "THU_START_TIME",
        "THU_END_TIME",
        "FRI_START_TIME",
        "FRI_END_TIME",
        "SAT_START_TIME",
        "SAT_END_TIME",
        "SUN_START_TIME",
        "SUN_END_TIME",
        "EXCEPTION_TEXT",
        "TEXT",
        "VOICE",
        "VOICE_ONLY",
        "PHONE",
        "EMAIL",
        "LOCATION",
        "LATITUDE",
        "LONGITUDE",
        "REF_URL",
        "LANGUAGES",
        "MEDIA",
        "PROCESS_AGENT_ID",
        "PROCESS_ID"
        ]
    elif(fleName == 'Unstructured.xlsx'):
        columnNames = [
        # "SUBJECT_AREA",
        # "SAMPLE_QUESTION",
        "INTENT",
        "ENTITY_NAME",
        "COPIED_FROM",
        "SECONDARY_ENTITY_NAME",
        "KEYWORD",
        "TEXT",
        "VOICE",
        # "VOICE_ONLY",
        "REF_URL",
        "MEDIA",
        "LANGUAGES",
        "PROCESS_AGENT_ID",
        "PROCESS_ID"
        ]
    df = pd.read_excel(fle)
    for col in columnNames:
        if col not in df.columns:
            raise KeyError("column " + col + " not present in " + fleName)

       	
	
